const { EmbedBuilder } = require('discord.js');
module.exports = {
  name: 'secret_key',
  callback: async (client, interaction) => {
    const embed = new EmbedBuilder()
      .setTitle('Secret key info')
      .setDescription('Secret keys can be used to get OTP (one-time-code) to log into a Microsoft Account with. An example of a secret key is: iezp fav6 t6ga gjsu. Some of the ways you can obtain the OTP are:\n * https://zyger.net/middleman/2fa/\n* /authcode\n* 2FA button on embeds\n\n**How to log in with it?**\n Go to https://login.live.com, type in your primary email and password, then it should prompt you to enter a code. Enter the code generated by any of the 3 options above to login (using the secret key!)')
      .setColor('#c6d2dd');
    await interaction.reply({ embeds: [embed], ephemeral: true });
  }
};
